# Generated by Django 2.2 on 2021-08-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_app', '0003_auto_20210812_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
