# Generated by Django 2.2 on 2021-08-12 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snowboard_app', '0009_auto_20210812_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_who_favorited',
            field=models.ManyToManyField(related_name='products_user_favorited', to=settings.AUTH_USER_MODEL),
        ),
    ]
