# Generated by Django 2.2 on 2021-09-27 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_app', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='comments_user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
